#include "RTC.h"
uint8_t RTC::BCDtoBYTE(uint8_t BCD)
{
	uint8_t H = BCD >> 4;
	uint8_t L = BCD & 0x0F;
	return H * 10 + L;
}
void RTC::get_time(DATE_TIME* Time)
{
	out8(CMOS_ADDRESS_PORT, NMI_DISABLE_FLAG | RTC_REG_SECONDS);
	Time->seconds = BCDtoBYTE(in8(CMOS_DATA_PORT));
	out8(CMOS_ADDRESS_PORT, NMI_DISABLE_FLAG | RTC_REG_MIMUTES);
	Time->minutes = BCDtoBYTE(in8(CMOS_DATA_PORT));
	out8(CMOS_ADDRESS_PORT, NMI_DISABLE_FLAG | RTC_REG_HOURS);
	Time->hours = BCDtoBYTE(in8(CMOS_DATA_PORT));
	out8(CMOS_ADDRESS_PORT, NMI_DISABLE_FLAG | RTC_REG_WEEKDAY);
	Time->day_of_week = BCDtoBYTE(in8(CMOS_DATA_PORT));
	out8(CMOS_ADDRESS_PORT, NMI_DISABLE_FLAG | RTC_REG_DAYOFMONTH);
	Time->day_of_month = BCDtoBYTE(in8(CMOS_DATA_PORT));
	out8(CMOS_ADDRESS_PORT, NMI_DISABLE_FLAG | RTC_REG_MONTH);
	Time->month = BCDtoBYTE(in8(CMOS_DATA_PORT));
	out8(CMOS_ADDRESS_PORT, NMI_DISABLE_FLAG | RTC_REG_YEAR);
	Time->year = BCDtoBYTE(in8(CMOS_DATA_PORT));
}