#pragma once

#define ERROR_SUCCESS               0
#define ERROR_UNDEFINED             1
#define ERROR_FILE_DOES_NOT_EXIST   2
#define ERROR_MOUNTPOINT_EXISTS     3
#define ERROR_EOF                   4
#define ERROR_INVALID_PARAMETER     5
#define ERROR_INVALID_EXECUTABLE    6
#define ERROR_LOADING_EXECUTABLE    7
#define ERROR_NO_ROOT_NODE          8
#define ERROR_INVALID_OPERATION     9
#define ERROR_FILE_ALREADY_EXISTS   10
#define ERROR_DEVICE_ALREADY_EXISTS 11
#define ERROR_DEVICE_DOESNOT_EXIST  12
#define ERROR_FS_ALREADY_EXISTS     13
#define ERROR_INVALID_HANDLE        14
#define ERROR_INVALID_PID           15
#define ERROR_READING_ARGS          16
#define ERROR_ACCESS_DENIED         17
#define ERROR_CONNECTION_DENIED     18
#define ERROR_CONNECTION_CLOSED     19
#define ERROR_CONNECTION_TIMEOUT    20