SET(CMAKE_REAL_SYSTEM_NAME ${CMAKE_SYSTEM_NAME})
SET(CMAKE_REAL_SYSTEM_VERSION ${CMAKE_SYSTEM_VERSION})
SET(CMAKE_SYSTEM_NAME "Generic")
SET(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_C_COMPILER_ "clang")
SET(CMAKE_CXX_COMPILER "clang++")
SET(CMAKE_C_COMPILER_ID "Clang")
SET(CMAKE_CXX_COMPILER_ID "Clang")

SET(CMAKE_CXX_STANDARD 20)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS ON)