#pragma once

#define ERROR_SUCCESS             0
#define ERROR_UNDEFINED           1
#define ERROR_FILE_DOES_NOT_EXIST 2
#define ERROR_MOUNTPOINT_EXISTS   3
#define ERROR_EOF                 4
#define ERROR_INVALID_PARAMETERS  5
#define ERROR_INVALID_EXECUTABLE  6
#define ERROR_LOADING_EXECUTABLE  7
#define ERROR_NO_ROOT_NODE        8
#define ERROR_INVALID_OPERATION   9
#define ERROR_FILE_ALREADY_EXISTS 10
